meta:
  rds_broker:
    medium_postgres_rds_properties:
      db_instance_class: "db.m4.large"
      engine: "postgres"
      engine_version: "9.5.2"
      storage_type: "gp2"
      allocated_storage: 20
      auto_minor_version_upgrade: true
      multi_az: false
      publicly_accessible: false
      copy_tags_to_snapshot: true
      skip_final_snapshot: true
      backup_retention_period: 7
      db_subnet_group_name: (( grab terraform_outputs.rds_broker_dbs_subnet_group ))
      vpc_security_group_ids:
        - (( grab terraform_outputs.rds_broker_dbs_security_group_id ))
      db_parameter_group_name: (( grab terraform_outputs.rds_broker_postgres95_db_parameter_group ))

releases:
  - name: aws-broker
    version: 0.0.8

jobs:
  - name: rds_broker
    azs: [z1, z2]
    instances: 2
    vm_type: rds_broker
    stemcell: default
    templates:
      - name: rds-broker
        release: aws-broker
    networks:
      - name: cf
    properties:
      rds-broker:
        aws_access_key_id: ""
        aws_secret_access_key: ""
        aws_region: "eu-west-1"
        password: (( grab secrets.rds_broker_admin_password ))
        state_encryption_key: (( grab secrets.rds_broker_state_encryption_key ))
        db_prefix: "rdsbroker"
        master_password_seed: (( grab secrets.rds_broker_master_password_seed ))
        broker_name: "(( grab terraform_outputs.environment ))"
        catalog:
          services:
            - id: "ce71b484-d542-40f7-9dd4-5526e38c81ba"
              name: "postgres"
              description: "AWS RDS PostgreSQL service"
              bindable: true
              tags:
                - "postgres"
                - "relational"
              metadata:
                displayName: "AWS RDS Postgres"
                imageUrl: ""
                longDescription: "AWS RDS postgres service"
                providerDisplayName: "Amazon Web Services"
                documentationUrl: "https://aws.amazon.com/documentation/rds/"
                supportUrl: "https://forums.aws.amazon.com/forum.jspa?forumID=60"
              plan_updateable: false
              plans:
                - id: "9b882524-ab58-4c18-b501-d2a3f4619104"
                  name: "M-dedicated-9.5"
                  description: "20GB Storage, Dedicated Instance, Max 500 Concurrent Connections. Postgres Version 9.5"
                  free: false
                  metadata:
                    costs:
                      - amount:
                          usd: 0.201
                        unit: "HOUR"
                    bullets:
                      - "Dedicated Postgres 9.5 server"
                      - "AWS RDS"
                  rds_properties:
                    inject: (( inject meta.rds_broker.medium_postgres_rds_properties ))

                - id: "bf5b99c2-7990-4b66-b341-1bb83566d76e"
                  name: "M-HA-dedicated-9.5"
                  description: "20GB Storage, Dedicated Instance, Highly Available, Max 500 Concurrent Connections. Postgres Version 9.5"
                  free: false
                  metadata:
                    costs:
                      - amount:
                          usd: 0.402
                        unit: "HOUR"
                    bullets:
                      - "Dedicated Postgres 9.5 server"
                      - "AWS RDS"
                  rds_properties:
                    inject: (( inject meta.rds_broker.medium_postgres_rds_properties ))
                    multi_az: true

properties:
  cc:
    security_group_definitions:
      - name: rds_broker_instances
        rules:
          - protocol: tcp
            destination: (( grab terraform_outputs.aws_backing_service_cidr_all ))
            ports: '5432'

    default_running_security_groups:
      - (( append ))
      - "rds_broker_instances"
    default_staging_security_groups:
      - (( append ))
      - "rds_broker_instances"
