---
resource_pools:
- name: vms
  network: private
  stemcell:
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3232.13
    sha1: 477371a335d172f4728c7a8806448edb9703104c
  cloud_properties:
    instance_type: t2.medium
    ephemeral_disk: {size: 40_000, type: gp2}
    availability_zone: (( grab terraform_outputs.bosh_az ))
    iam_instance_profile: bosh-director
  env:
    bosh:
      password: (( grab secrets.bosh_vcap_password ))
disk_pools:
- name: disks
  cloud_properties:
    type: gp2

networks:
- name: private
  type: manual
  subnets:
  - range: (( grab terraform_outputs.bosh_subnet_cidr ))
    gateway: (( grab terraform_outputs.bosh_default_gw ))
    dns: [10.0.0.2]
    cloud_properties:
      subnet: (( grab terraform_outputs.bosh_subnet_id ))
      security_groups:
      - (( grab terraform_outputs.bosh_security_group ))
- name: public
  type: vip
