---
releases:
- name: collectd
  sha1: 5e5c196f9c95fe12eb17bba0f40fdaecaddd6424
  url: https://github.com/alphagov/paas-collectd-boshrelease/releases/download/0.4/collectd-0.4.tgz

jobs:
- name: bosh
  templates:
  - {name: collectd, release: collectd}

properties:
  collectd:
    hostname_prefix: bosh_
    interval: (( grab meta.collectd.interval ))
    config: (( grab meta.collectd.config ))
