---
name: concourse

releases:
  - name: concourse
    url: https://bosh.io/d/github.com/concourse/concourse?v=0.74.0
    sha1: c99ef709e9d4468ac25cca31dd5be1444417011d
  - name: garden-linux
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release?v=0.334.0
    sha1: 85170c5089fa4ff317f139c2f1da024860dbea85
  # When updating the version of the CPI here, the version used in the
  # bosh-init container must also be updated so that the cached CPI compile
  # will be used.
  - name: bosh-aws-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=52
    sha1: dc4a0cca3b33dce291e4fbeb9e9948b6a7be3324

resource_pools:
  - name: concourse
    network: concourse
    stemcell:
      url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3232.13
      sha1: 477371a335d172f4728c7a8806448edb9703104c
    cloud_properties:
      instance_type: t2.medium
      availability_zone: (( grab terraform_outputs.zone0 ))
      iam_instance_profile: deployer-concourse
      elbs:
      - (( grab terraform_outputs.concourse_elb_name ))
      ephemeral_disk:
        size: 50240
        type: gp2
    env:
      bosh:
        password: (( grab secrets.concourse_vcap_password ))

disk_pools:
  - name: db
    disk_size: 10240
    cloud_properties:
      type: gp2

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.0.0/24
        dns: [10.0.0.2]
        gateway: 10.0.0.1
        reserved:
        - 10.0.0.0 - 10.0.0.9
        static:
        - 10.0.0.10 - 10.0.0.20

        cloud_properties:
          subnet: (( grab terraform_outputs.subnet0_id ))
  - name: public
    type: vip

jobs:
  - name: concourse
    instances: 1
    resource_pool: concourse
    persistent_disk_pool: db

    templates:
      - {release: concourse, name: postgresql}
      - {release: concourse, name: atc}
      - {release: concourse, name: groundcrew}
      - {release: concourse, name: tsa}
      - {release: concourse, name: baggageclaim}
      - {release: garden-linux, name: garden}

    networks:
      - name: public
        static_ips:
        - (( grab terraform_outputs.concourse_elastic_ip ))
      - name: concourse
        static_ips: (( static_ips(0) ))
        default: [dns, gateway]

    properties:
      atc:
        external_url: (( concat "https://" terraform_outputs.concourse_dns_name ))
        basic_auth_username: admin
        basic_auth_password: (( grab secrets.concourse_atc_password ))
        publicly_viewable: true
        postgresql:
          address: 127.0.0.1:5432
          role: &atc-role
            name: atc
            password: dummy-password

      postgresql:
        databases: [{name: atc}]
        roles:
          - *atc-role
      tsa:
        forward_host: 127.0.0.1
        atc:
          address: 127.0.0.1:8080
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        graph_cleanup_threshold_in_mb: 3072
      groundcrew:
        baggageclaim:
          url: "http://127.0.0.1:7788"
        tsa:
          host: 127.0.0.1
        additional_resource_types:
          - { type: s3-iam, image: "docker:///governmentpaas/s3-resource" }
          - { type: semver-iam, image: "docker:///governmentpaas/semver-resource" }
          - { type: git-gpg, image: "docker:///governmentpaas/git-resource" }

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: (( grab terraform_outputs.concourse_elastic_ip ))
    port: 22
    user: vcap
    private_key: id_rsa # Appears to be relative to working dir

  mbus: (( concat "https://mbus:" secrets.concourse_nats_password "@" terraform_outputs.concourse_elastic_ip ":6868" ))

  properties:
    aws:
      credentials_source: env_or_profile
      default_key_name: (( grab terraform_outputs.key_pair_name ))
      default_security_groups:
      - (( grab terraform_outputs.concourse_security_group ))
      - (( grab terraform_outputs.ssh_security_group ))
      region: (( grab terraform_outputs.region ))
    agent:
      mbus: (( concat "https://mbus:" secrets.concourse_nats_password "@0.0.0.0:6868" ))
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: [0.pool.ntp.org, 1.pool.ntp.org]
